
//运单静态数据
var waybillListDa= [{
        "receipttime": "2022-07-05 00:08:09",
        "driverId":"ceshi",
        "distance": 12,
        "materialNo": "321",
        "origin": "Ffff",
        "receiving": "Dddd",
        "receivingStakeNum": 7,
        "motorcadeName": "B2",
        "carNo": "黑AN2769",
        "projectCode": "60000037",
        "consignorId": "xushiquan",
        "dbid": 129,
        "consigneeId": "xushiquanshou",
        "deliveryRemark": "Aaaa",
        "originStakeNumMeter": 6,
        "quantity": "11",
        "loadStakeNum": 3,
        "originStakeNum": 5,
        "gmtCreate": "2022-07-05 00:03:33",
        "materialName": "土",
        "loadStakeNumMeter": 4,
        "deliverytime": "2022-07-05 00:03:33",
        "projectName": "吉林至黑河国家高速公路黑龙江省山河（吉黑省界）至哈尔滨",
        "workAreaName": "B2工区",
        "receivingStakeNumMeter": 8,
        "waybillNo": "20220705000333053914",
        "status": "1"
    },
    {
        "receipttime": "2022-05-20 11:08:35",
        "driverId":"ceshi",
        "distance": 11,
        "materialNo": "321",
        "origin": "1",
        "receiving": "1",
        "receivingStakeNum": 1,
        "adjustRemark": "",
        "motorcadeName": "B2",
        "carNo": "黑AN2769",
        "projectCode": "60000037",
        "consignorId": "fly",
        "dbid": 99,
        "consigneeId": "yanshi",
        "deliveryRemark": "",
        "originStakeNumMeter": 1,
        "quantity": "11",
        "loadStakeNum": 1,
        "receiptRemark": "",
        "originStakeNum": 1,
        "gmtCreate": "2022-05-20 11:01:29",
        "materialName": "土",
        "loadStakeNumMeter": 1,
        "deliverytime": "2022-05-04 00:00:00",
        "projectName": "吉林至黑河国家高速公路黑龙江省山河（吉黑省界）至哈尔滨",
        "workAreaName": "B2工区",
        "receivingStakeNumMeter": 1,
        "waybillNo": "20220520110128848923",
        "status": "1"
    },
    {
        "receipttime": "2022-05-20 11:08:35",
        "driverId":"ceshi",
        "distance": 11,
        "materialNo": "321",
        "origin": "1",
        "receiving": "1",
        "receivingStakeNum": 1,
        "adjustRemark": "",
        "motorcadeName": "B2",
        "carNo": "黑AN2769",
        "projectCode": "60000037",
        "consignorId": "fly",
        "dbid": 130,
        "consigneeId": "yanshi",
        "deliveryRemark": "",
        "originStakeNumMeter": 1,
        "quantity": "11",
        "loadStakeNum": 1,
        "receiptRemark": "",
        "originStakeNum": 1,
        "gmtCreate": "2022-05-20 11:01:29",
        "materialName": "土",
        "loadStakeNumMeter": 1,
        "deliverytime": "2022-05-04 00:00:00",
        "projectName": "吉林至黑河国家高速公路黑龙江省山河（吉黑省界）至哈尔滨",
        "workAreaName": "B2工区",
        "receivingStakeNumMeter": 1,
        "waybillNo": "20220520110128848923",
        "status": "1"
    },
    {
        "receipttime": "2022-05-20 11:08:35",
        "driverId":"ceshi",
        "distance": 11,
        "materialNo": "321",
        "origin": "1",
        "receiving": "1",
        "receivingStakeNum": 1,
        "adjustRemark": "",
        "motorcadeName": "B2",
        "carNo": "黑AN2769",
        "projectCode": "60000037",
        "consignorId": "fly",
        "dbid": 131,
        "consigneeId": "yanshi",
        "deliveryRemark": "",
        "originStakeNumMeter": 1,
        "quantity": "11",
        "loadStakeNum": 1,
        "receiptRemark": "",
        "originStakeNum": 1,
        "gmtCreate": "2022-05-20 11:01:29",
        "materialName": "土",
        "loadStakeNumMeter": 1,
        "deliverytime": "2022-05-04 00:00:00",
        "projectName": "吉林至黑河国家高速公路黑龙江省山河（吉黑省界）至哈尔滨",
        "workAreaName": "B2工区",
        "receivingStakeNumMeter": 1,
        "waybillNo": "20220520110128848923",
        "status": "1"
    }
    ];	


   